document.writeln("<footer class=\'footer-area bg-gray pt-100 pb-70\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'copyright mb-30\'>");
document.writeln("                    <div class=\'footer-logo\'>");
document.writeln("                        <a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/\'>");
document.writeln("                            <img alt=\'\' src=\'https://luoyunofficial.github.io/cloudervallge/assets/images/英-黑logo.png\' height=\'60\' width=\'150\'>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <p class=\'rights\'><span>&copy;&nbsp;</span><span class=\'copyright-year\'> </span><span> LuoYun</span><br/><a target=\'_blank\' href=\'https://www.mobanwang.com/\' title=\'Template\'>Template</a></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-30\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>ABOUT US</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("						    <li><a href=\'https://luoyunofficial.github.io/cloudervallge/about\'>ClouderVallge</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/about\'>LuoYun</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/contact\'>Contact us</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/privacy\'>LuoYun Privacy</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/cloudervallge/terms\'>Terms of Services</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-50\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>MORE</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/languages\'>Languages</a></li>");
document.writeln("                            <!--li><a href=\'#\'>Support Policy</a></li>");
document.writeln("                            <li><a href=\'#\'>Size guide</a></li>");
document.writeln("                            <li><a href=\'#\'>FAQs</a></li-->");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-75\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>FOLLOW US</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'#\'>WeChat Account</a></li>");
document.writeln("                            <li><a href=\'https://space.bilibili.com/3461564260682658\'><span title=\'People cannot understand Chinese may be difficult in understanding.\' data-title>Bilibili</span></a></li>");
document.writeln("                            <li><a href=\'#\' title=\'You will be redirected to rednote.\' data-title>rednote</a></li>");
document.writeln("                            <li><a href=\'https://www.youtube.com/@cloudervallge\'>YouTube</a></li>");
document.writeln("							<li><a href=\'https://github.com/LuoYunOfficial/\'>GitHub(LuoYun)</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-4 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-70\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>SUBSCRIBE</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'subscribe-style\'>");
document.writeln("                        <p>Get the latest news, announcements and information by adding the RSS feed.</p>");
document.writeln("                        <div id=\'mc_embed_signup\' class=\'subscribe-form\'>");
document.writeln("                            <a id=\'mc-embedded-subscribe\' href=\'https://luoyunofficial.github.io/cloudervallge-blog/feed.xml\'>RSS URL</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");