document.writeln("<header class=\'header-area header-in-container clearfix\'>");
document.writeln("    <div class=\'header-top-area\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'header-top-wap\'>");
document.writeln("                <div class=\'language-currency-wrap\'>");
document.writeln("                    <div class=\'same-language-currency language-style\'>");
document.writeln("                        <a href=\'https://luoyunofficial.github.io/cloudervallge/\'>English <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("                        <div class=\'lang-car-dropdown\'>");
document.writeln("                            <ul>");
document.writeln("                                <li><a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/\'>Chinese </a></li>");
document.writeln("                                <li><a href=\'https://luoyunofficial.github.io/cloudervallge/ja-jp/\'>Japanese </a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'same-language-currency\'>");
document.writeln("                        <p>Nice to meet you!</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'header-offer\'>");
document.writeln("                    <p>Now we need your <span>help</span></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'header-bottom sticky-bar header-res-padding\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("            <div class=\'col-xl-2 col-lg-2 col-md-6 col-4\'>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <a href=\'https://luoyunofficial.github.io/cloudervallge/\'>");
document.writeln("                        <img alt=\'\' src=\'https://luoyunofficial.github.io/cloudervallge/assets/images/英-黑logo.png\' height=\'26\' width=\'70\'>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-xl-8 col-lg-8 d-none d-lg-block\'>");
document.writeln("                <div class=\'main-menu\'>");
document.writeln("                    <nav>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/\'>Home</a></li>");
document.writeln("                            <!--li><a href=\'shop.html\'> Shop <i class=\'fa fa-angle-down\'></i> </a>");
document.writeln("                                <ul class=\'mega-menu\'>");
document.writeln("                                    <li>");
document.writeln("                                        <ul>");
document.writeln("                                            <li class=\'mega-menu-title\'><a href=\'#\'>shop layout</a></li>");
document.writeln("                                            <li><a href=\'shop.html\'>standard style</a></li>");
document.writeln("                                            <li><a href=\'shop-filter.html\'>Grid filter style</a></li>");
document.writeln("                                            <li><a href=\'shop-grid-2-col.html\'>Grid 2 column</a></li>");
document.writeln("                                            <li><a href=\'shop-no-sidebar.html\'>Grid No sidebar</a></li>");
document.writeln("                                            <li><a href=\'shop-grid-fw.html\'>Grid full wide </a></li>");
document.writeln("                                            <li><a href=\'shop-right-sidebar.html\'>Grid right sidebar</a></li>");
document.writeln("                                            <li><a href=\'shop-list.html\'>list 1 column box </a></li>");
document.writeln("                                            <li><a href=\'shop-list-fw.html\'>list 1 column full wide </a></li>");
document.writeln("                                            <li><a href=\'shop-list-fw-2col.html\'>list 2 column  full wide</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </li>");
document.writeln("                                    <li>");
document.writeln("                                        <ul>");
document.writeln("                                            <li class=\'mega-menu-title\'><a href=\'#\'>product details</a></li>");
document.writeln("                                            <li><a href=\'product-details.html\'>tab style 1</a></li>");
document.writeln("                                            <li><a href=\'product-details-2.html\'>tab style 2</a></li>");
document.writeln("                                            <li><a href=\'product-details-3.html\'>tab style 3</a></li>");
document.writeln("                                            <li><a href=\'product-details-4.html\'>sticky style</a></li>");
document.writeln("                                            <li><a href=\'product-details-5.html\'>gallery style </a></li>");
document.writeln("                                            <li><a href=\'product-details-slider-box.html\'>Slider style</a></li>");
document.writeln("                                            <li><a href=\'product-details-affiliate.html\'>affiliate style</a></li>");
document.writeln("                                            <li><a href=\'product-details-6.html\'>fixed image style </a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </li>");
document.writeln("                                    <li>");
document.writeln("                                        <ul>");
document.writeln("                                            <li class=\'mega-menu-img\'><a href=\'shop.html\'><img src=\'assets/img/banner/banner-12.png\' alt=\'\'></a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("                            </li-->");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/character\'>Character</a></li>");
document.writeln("                            <!--li><a href=\'#\'> Pages <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("                                <ul class=\'submenu\'>");
document.writeln("                                    <li><a href=\'#\'>about us</a></li>");
document.writeln("                                    <li><a href=\'#\'>cart page</a></li>");
document.writeln("                                    <li><a href=\'#\'>checkout </a></li>");
document.writeln("                                    <li><a href=\'#\'>wishlist </a></li>");
document.writeln("                                    <li><a href=\'#\'>my account</a></li>");
document.writeln("                                    <li><a href=\'#\'>login / register </a></li>");
document.writeln("                                    <li><a href=\'#\'>contact us </a></li>");
document.writeln("                                    <li><a href=\'#\'>404 page </a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li-->");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge-blog/\'>Blog</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/about\'> About </a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/contact\'> Contact</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/zh-cn/\'>LuoYun</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'mobile-menu-area\'>");
document.writeln("            <div class=\'mobile-menu\'>");
document.writeln("                <nav id=\'mobile-menu-active\'>");
document.writeln("                    <ul class=\'menu-overflow\'>");
document.writeln("                        <li><a href=\'https://luoyunofficial.github.io/cloudervallge/\'>Home</a></li>");
document.writeln("                        <!--li><a href=\'shop.html\'>Shop</a>");
document.writeln("                            <ul>");
document.writeln("                                <li><a href=\'#\'>shop layout</a>");
document.writeln("                                    <ul>");
document.writeln("                                        <li><a href=\'shop.html\'>standard style</a></li>");
document.writeln("                                        <li><a href=\'shop-filter.html\'>Grid filter style</a></li>");
document.writeln("                                        <li><a href=\'shop-grid-2-col.html\'>Grid 2 column</a></li>");
document.writeln("                                        <li><a href=\'shop-no-sidebar.html\'>Grid No sidebar</a></li>");
document.writeln("                                        <li><a href=\'shop-grid-fw.html\'>Grid full wide </a></li>");
document.writeln("                                        <li><a href=\'shop-right-sidebar.html\'>Grid right sidebar</a></li>");
document.writeln("                                        <li><a href=\'shop-list.html\'>list 1 column box </a></li>");
document.writeln("                                        <li><a href=\'shop-list-fw.html\'>list 1 column full wide </a></li>");
document.writeln("                                        <li><a href=\'shop-list-fw-2col.html\'>list 2 column  full wide</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>product details</a>");
document.writeln("                                    <ul>");
document.writeln("                                        <li><a href=\'product-details.html\'>tab style 1</a></li>");
document.writeln("                                        <li><a href=\'product-details-2.html\'>tab style 2</a></li>");
document.writeln("                                        <li><a href=\'product-details-3.html\'>tab style 3</a></li>");
document.writeln("                                        <li><a href=\'product-details-4.html\'>sticky style</a></li>");
document.writeln("                                        <li><a href=\'product-details-5.html\'>gallery style </a></li>");
document.writeln("                                        <li><a href=\'product-details-slider-box.html\'>Slider style</a></li>");
document.writeln("                                        <li><a href=\'product-details-affiliate.html\'>affiliate style</a></li>");
document.writeln("                                        <li><a href=\'product-details-6.html\'>fixed image style </a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li-->");
document.writeln("                        <li><a href=\'https://luoyunofficial.github.io/cloudervallge/character\'>Character</a></li>");
document.writeln("                        <!--li><a href=\'#\'>Pages</a>");
document.writeln("                            <ul>");
document.writeln("                                <li><a href=\'about.html\'>about us</a></li>");
document.writeln("                                <li><a href=\'cart-page.html\'>cart page</a></li>");
document.writeln("                                <li><a href=\'checkout.html\'>checkout </a></li>");
document.writeln("                                <li><a href=\'wishlist.html\'>wishlist </a></li>");
document.writeln("                                <li><a href=\'my-account.html\'>my account</a></li>");
document.writeln("                                <li><a href=\'login-register.html\'>login / register </a></li>");
document.writeln("                                <li><a href=\'contact.html\'>contact us </a></li>");
document.writeln("                                <li><a href=\'404.html\'>404 page </a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li-->");
document.writeln("                        <li><a href=\'https://luoyunofficial.github.io/cloudervallge-blog/\'>Blog</a></li>");
document.writeln("                        <li><a href=\'https://luoyunofficial.github.io/cloudervallge/about\'>About</a></li>");
document.writeln("                        <li><a href=\'https://luoyunofficial.github.io/cloudervallge/contact\'>Contact</a></li>");
document.writeln("                    </ul>");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");