document.writeln("<style>");
document.writeln("        [data-title]{");
document.writeln("            position: relative;");
document.writeln("            margin: 0 0px;");
document.writeln("        }");
document.writeln("        [data-title]:after{");
document.writeln("            content: attr(data-title);");
document.writeln("            position: absolute;");
document.writeln("            left: 50%;");
document.writeln("            bottom: 100%;");
document.writeln("            transform: translate(-50%,0);");
document.writeln("            color: #fff;");
document.writeln("            text-shadow: 0 -1px 0px black;");
document.writeln("            box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3);");
document.writeln("            background: #383838;");
document.writeln("            border-radius: 2px;");
document.writeln("            padding: 3px 10px;");
document.writeln("            font-size: 12px;");
document.writeln("            white-space: nowrap;");
document.writeln("            transition:all .3s;");
document.writeln("            opacity: 0;");
document.writeln("            visibility: hidden;");
document.writeln("        }");
document.writeln("        [data-title]:hover:after{");
document.writeln("            transition-delay: 100ms;");
document.writeln("            visibility: visible;");
document.writeln("            transform: translate(-50%,-6px);");
document.writeln("            opacity: 1;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("    <!-- Bootstrap CSS -->");
document.writeln("    <link rel=\'stylesheet\' href=\'https://luoyunofficial.github.io/cloudervallge/assets/css/bootstrap.min.css\'>");
document.writeln("    <!-- Icon Font CSS -->");
document.writeln("    <link rel=\'stylesheet\' href=\'https://luoyunofficial.github.io/cloudervallge/assets/css/icons.min.css\'>");
document.writeln("    <!-- Plugins CSS -->");
document.writeln("    <link rel=\'stylesheet\' href=\'https://luoyunofficial.github.io/cloudervallge/assets/css/plugins.css\'>");
document.writeln("    <!-- Main Style CSS -->");
document.writeln("    <link rel=\'stylesheet\' href=\'https://luoyunofficial.github.io/cloudervallge/assets/css/style.css\'>");
document.writeln("<script>");
document.writeln("function dataTitle(){");
document.writeln("    var data_title = document.querySelectorAll(\'[data-title]\');");
document.writeln("    console.log(data_title);");
document.writeln("    for (var i = 0; i < data_title.length; i++){");
document.writeln("        data_title[i].setAttribute(\'data-title\',data_title[i].getAttribute(\'title\'));");
document.writeln("        data_title[i].removeAttribute(\'title\');");
document.writeln("    }");
document.writeln("}");
document.writeln("dataTitle();");
document.writeln("</script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/modernizr-3.11.7.min.js\'></script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/jquery-v3.6.0.min.js\'></script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/jquery-migrate-v3.3.2.min.js\'></script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/bootstrap.min.js\'></script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/plugins.js\'></script>");
document.writeln("<script src=\'https://luoyunofficial.github.io/js/script.js\'></script>");
document.writeln("<!-- Ajax Mail -->");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/ajax-mail.js\'></script>");
document.writeln("<!-- Main JS -->");
document.writeln("<script src=\'https://luoyunofficial.github.io/cloudervallge/assets/js/main.js\'></script>");