document.writeln("<footer class=\'footer-area bg-gray pt-100 pb-70\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'copyright mb-30\'>");
document.writeln("                    <div class=\'footer-logo\'>");
document.writeln("                        <a href=\'https://luoyunofficial.github.io/cloudervallge/ja-jp/\'>");
document.writeln("                            <img alt=\'\' src=\'https://luoyunofficial.github.io/cloudervallge/assets/images/英-黑logo.png\' height=\'60\' width=\'150\'>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <p class=\'rights\'><span>©&nbsp;</span><span class=\'copyright-year\'>2025</span><span> LuoYun</span><br><a target=\'_blank\' href=\'https://www.mobanwang.com/\' title=\'テンプレート\'>テンプレート</a></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-30\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>私たちについて</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("						    <li><a href=\'https://luoyunofficial.github.io/cloudervallge/ja-jp/about\'>ClouderVallge</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/ja-jp/about\'>LuoYun</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/ja-jp/contact\'>お問い合わせ</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/ja-jp/privacy\'>LuoYun プライバシーポリシー</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/cloudervallge/ja-jp/terms\'>ユーザーサービス契約</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-50\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>もっと</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/languages\'>Languages | 言語</a></li>");
document.writeln("                            <!--li><a href=\'#\'>Support Policy</a></li>");
document.writeln("                            <li><a href=\'#\'>Size guide</a></li>");
document.writeln("                            <li><a href=\'#\'>FAQs</a></li-->");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-75\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>フォロー</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'#\'>WeChat公式アカウント</a></li>");
document.writeln("                            <li><a href=\'https://space.bilibili.com/3461564260682658\'><span data-title=\'中国語を話さない人には理解できないかもしれません。\'>ビリビリ</span></a></li>");
document.writeln("                            <li><a href=\'#\' data-title=\'中国語と英語のみでご利用いただけます。\'>rednote</a></li>");
document.writeln("                            <li><a href=\'https://www.youtube.com/@cloudervallge\'>YouTube</a></li>");
document.writeln("							<li><a href=\'https://github.com/LuoYunOfficial/\'>GitHub(LuoYun)</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-4 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-70\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>サブスクリプション</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'subscribe-style\'>");
document.writeln("                        <p>RSS フィードを追加して、最新のニュース、お知らせ、情報を入手してください。</p>");
document.writeln("                        <div id=\'mc_embed_signup\' class=\'subscribe-form\'>");
document.writeln("                            <a id=\'mc-embedded-subscribe\' href=\'https://luoyunofficial.github.io/cloudervallge-blog/feed.xml\'>RSS URL</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");