document.writeln("<footer class=\'footer-area bg-gray pt-100 pb-70\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'copyright mb-30\'>");
document.writeln("                    <div class=\'footer-logo\'>");
document.writeln("                        <a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/\'>");
document.writeln("                            <img alt=\'\' src=\'https://luoyunofficial.github.io/cloudervallge/assets/images/中-黑logo.png\' height=\'60\' width=\'150\'>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <p class=\'rights\'><span>&copy;&nbsp;</span><span class=\'copyright-year\'> </span><span> LuoYun</span><br/><a target=\'_blank\' href=\'https://www.mobanwang.com/\' title=\'网站模板\'>网站模板</a></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-30\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>关于我们</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("						    <li><a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/about\'>《云墟协奏》</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/zh-cn/about\' title=\'使用部分运营商网络可能无法打开该页面。\' data-title>LuoYun</a></li>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/contact\'>联系我们</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/zh-cn/privacy\' title=\'使用部分运营商网络可能无法打开该页面。\' data-title>LuoYun 隐私政策</a></li>");
document.writeln("							<li><a href=\'https://luoyunofficial.github.io/cloudervallge/zh-cn/terms\'>用户服务协议</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-4 col-sm-4\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-50\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>更多</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'https://luoyunofficial.github.io/cloudervallge/languages\'>Languages | 语言</a></li>");
document.writeln("                            <!--li><a href=\'#\'>Support Policy</a></li>");
document.writeln("                            <li><a href=\'#\'>Size guide</a></li>");
document.writeln("                            <li><a href=\'#\'>FAQs</a></li-->");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-2 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-75\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>关注我们</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'footer-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'#\'>微信公众号</a></li>");
document.writeln("                            <li><a href=\'https://space.bilibili.com/3461564260682658\'><span title=\'将跳转至其他页面。\' data-title>哔哩哔哩</span></a></li>");
document.writeln("                            <li><a href=\'https://www.xiaohongshu.com/user/profile/64dcc6890000000001004c42\' title=\'将跳转至其他页面。\' data-title>小红书</a></li>");
document.writeln("                            <li><a href=\'https://www.youtube.com/@cloudervallge\' title=\'该页面在当前地区可能无法打开。\' data-title>YouTube</a></li>");
document.writeln("							<li><a href=\'https://github.com/LuoYunOfficial/\' title=\'使用部分运营商网络可能无法打开该页面。\' data-title>GitHub(LuoYun)</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-4 col-md-6 col-sm-6\'>");
document.writeln("                <div class=\'footer-widget mb-30 ml-70\'>");
document.writeln("                    <div class=\'footer-title\'>");
document.writeln("                        <h3>订阅我们的公告</h3>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'subscribe-style\'>");
document.writeln("                        <p>通过添加RSS源以获得最新的资讯，公告和信息。</p>");
document.writeln("                        <div id=\'mc_embed_signup\' class=\'subscribe-form\'>");
document.writeln("                            <a id=\'mc-embedded-subscribe\' href=\'https://luoyunofficial.github.io/cloudervallge-blog/feed.xml\' title=\'使用部分运营商网络可能无法打开该页面。\' data-title>RSS订阅地址</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");
